name: flutter_modular_architecture

packages:
  - core/**
  - features/**
  - '*'

ide:
  intellij:
    true

scripts:

  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
    select-package:

  test:
    description: Run tests in a specific package.
    run: melos exec --concurrency=1 -- "flutter pub get && flutter test --reporter expanded"
    select-package:
      dir-exists:
        - "test/"

  format: dart format -o write .

dev_dependencies:
  lints: ^1.0.1
  mockito: ^5.0.10
  build_runner: ^2.0.4
  auto_route_generator: 2.1.0
