name: dependencies
description: A new Flutter project.
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  dartz: ^0.10.0-nullsafety.2
  cross_connectivity: ^3.0.3
  get_it: ^7.1.3
  auto_route: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10
  lints: ^1.0.1
  auto_route_generator: 2.1.0
  build_runner: ^2.0.4

flutter: